import {StyleSheet, Dimensions} from 'react-native';
const {height} = Dimensions.get('window');
import {
  responsiveHeight,
  responsiveWidth,
} from 'react-native-responsive-dimensions';
export const styles = StyleSheet.create({
  productImageDetailScreen: {
    resizeMode: 'center',
    width: responsiveWidth(95),
    height: height - 500,
    marginLeft: 10,
    borderRadius: 10,
    marginRight: 10,
    marginTop: 10,
  },
  productTitle: {
    fontSize: 20,
    color: '#000',
    marginTop: responsiveHeight(-20),
    marginLeft: responsiveWidth(4),
    fontWeight: '600',
  },
  productDescription: {
    fontSize: 16,
    color: '#808080',
    fontWeight: '500',
    marginTop: responsiveHeight(4),
    marginLeft: responsiveWidth(1),
    width: '90%',
    alignSelf: 'center',
  },
  price: {
    color: 'black',
    marginLeft: '6%',
    fontSize: 30,
    fontWeight: '600',
  },
  iconContainer: {
    width: 40,
    height: 40,
    backgroundColor: '#E2DFDF',
    borderRadius: 20,
    elevation: 5,
    position: 'absolute',
    top: 30,
    right: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  icon: {
    fontSize: responsiveHeight(3),
    color: 'red',
  },
  ratingConatiner: {
    backgroundColor: 'green',
    flexDirection: 'row',
    width: responsiveWidth(15),
    height: responsiveHeight(4),
    marginLeft: responsiveWidth(-120),
    marginTop: 40,
  },
  ratingText: {
    color: 'white',
    fontSize: responsiveHeight(2),
    fontWeight: '700',
    textAlign: 'center',
    paddingLeft: 5,
  },
  starIcon: {
    fontSize: responsiveHeight(2),
    color: 'white',
    marginTop: 2,
  },
  addToCartButton: {
    width: '80%',
    height: 50,
    backgroundColor: '#088F8F',
    borderRadius: 20,
    elevation: 5,
    marginTop: responsiveHeight(5),
    alignSelf: 'center',
    marginBottom: 20,
    justifyContent: 'center',
  },
  offerStyle: {
    color: 'red',
    fontSize: 30,
    fontWeight: '200',
    marginStart: 15,
  },
  offerContainer: {
    backgroundColor: 'maroon',
    position: 'absolute',
    width: 40,
    height: 40,
    padding: 5,
    marginLeft: 20,
    top: 30,
  },
  quantityButton: {
    padding: 5,
    borderWidth: 0.5,
    width: 30,
    height: 30,
    alignSelf: 'center',
    top: 20,
    left: 30,
  },
  quantityButtonText: {
    fontSize: 20,
    color: 'black',
    alignSelf: 'center',
    fontWeight: '900',
    top: -5,
  },
  quantityText: {
    fontSize: 20,
    color: 'black',
    alignSelf: 'center',
    fontWeight: '900',
    top: 20,
    left: 15,
    padding: 5,
  },
});
